#端口
#service名字
#eureka-client
#网关
server:
  port: 10010
spring:
  application:
    name: api-gateway
zuul:
  prefix: /api # 路由路径前缀
  routes:
    database: /database/** # 微服务的映射路径
    test: /test/**
    student: /proson/**
#    service2: /service2/** # 微服务的映射路径
    prosenStudent: /prosenStudent/** # 个人中心-学生的映射路径
    prosenTeacher: /prosenTeacher/** # 个人中心-教师的映射路径
#    communication: /chat/** # 微服务的映射路径
#    person: /person/** # 微服务的映射路径
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka